#!/usr/bin/python3
import os
import sys

class search():
    def __init__(self,ml):
        v = ml[0:]
        for i, j, n in os.walk('exp'):
            p = str(i).replace('(', '').replace(')', '').replace('[', '').replace(']', '').replace("'", '').replace(',',' ')
            a = p.rfind(v)
            if v in p:
                print(p[:a] + p[a:])

if __name__ == '__main__':
    search(sys.argv[1])
