#!/usr/bin/python3
import os
import sys

path = os.getcwd()
ml=sys.argv[1]
v = ml[0:]
for i, j, n in os.walk('exp'):
    p = str(i).replace('(', '').replace(')', '').replace('[', '').replace(']', '').replace("'", '').replace(',', ' ')
    a = p.rfind(v)
    if v in p:
        print(p[:a] + p[a:])
